- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
- Network:
    - Pi-hole:
        - abbr: PI
          href: http://192.168.1.171/admin
    - AdGuard:
        - abbr: AG
          href: http://192.168.1.111:30080
- Linux Servers:
    - Ubuntu Host (19):
        - abbr: U1
          href: http://192.168.1.19:9090
    - TrueNAS:
        - abbr: TN
          href: https://192.168.1.111/ui
    - TrueNAS Cockpit:
        - abbr: T1
          href: https://192.168.1.111:9090
    - Host 171 Cockpit:
        - abbr: H1
          href: http://192.168.1.171:9090
    - Host 18 Cockpit:
        - abbr: H2
          href: http://192.168.1.18:9090
    - Host 180 Cockpit:
        - abbr: H3
          href: http://192.168.1.180:9090
    - Host 181 Cockpit:
        - abbr: H4
          href: http://192.168.1.181:9090
- System Admin:
    - Webmin (19):
        - abbr: WM
          href: http://192.168.1.19:10000
    - Webmin (171):
        - abbr: W1
          href: http://192.168.1.171:10000
    - Webmin (18):
        - abbr: W2
          href: http://192.168.1.18:10000
