- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
- Network:
    - Pi-hole:
        - abbr: PI
          href: http://192.168.1.171/admin
    - AdGuard:
        - abbr: AG
          href: http://192.168.1.111:30004
- Linux Servers:
    - Cockpit 16:
        - abbr: C16
          href: https://192.168.1.16:9090
    - Cockpit 19:
        - abbr: C19
          href: https://192.168.1.19:9090
    - Cockpit 120:
        - abbr: C120
          href: https://192.168.1.120:9090
- System Admin:
    - Webmin 18:
        - abbr: WM
          href: http://192.168.1.18:10000
    - Webmin 19:
        - abbr: W19
          href: http://192.168.1.19:10000
- Homepage:
    - Dashboard:
        - abbr: HP
          href: http://192.168.1.19:3000
