- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
- Productivity:
    - Resume AI:
        - abbr: RA
          href: http://192.168.1.19:8501
- Network:
    - Pi-hole:
        - abbr: PI
          href: http://192.168.1.171/admin
    - AdGuard:
        - abbr: AG
          href: http://192.168.1.111:30004
    - Nx Witness:
        - abbr: NX
          href: http://192.168.1.111:30121
- Storage:
    - Syncthing:
        - abbr: SY
          href: http://192.168.1.111:20910
    - SMB:
        - abbr: SMB
          href: smb://192.168.1.16
    - NFS:
        - abbr: NFS
          href: nfs://192.168.1.16
- Media:
    - MeTube:
        - abbr: MT
          href: http://192.168.1.111:30094
- Monitoring:
    - Netdata:
        - abbr: ND
          href: http://192.168.1.111:20489
- Linux Servers:
    - Cockpit 16:
        - abbr: C16
          href: https://192.168.1.16:9090
    - Cockpit 18:
        - abbr: C18
          href: https://192.168.1.18:9090
    - Cockpit 19:
        - abbr: C19
          href: https://192.168.1.19:9090
    - Cockpit 120:
        - abbr: C120
          href: https://192.168.1.120:9090
- System Admin:
    - Webmin 18:
        - abbr: WM
          href: http://192.168.1.18:10000
    - Webmin 19:
        - abbr: W19
          href: http://192.168.1.19:10000
- Homepage:
    - Dashboard:
        - abbr: HP
          href: http://192.168.1.19:3000
