---
# Widgets

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short

- resources:
    cpu: true
    memory: true
    disk: /

- openmeteo:
    label: Home
    latitude: 39.9259
    longitude: -75.0305
    timezone: America/New_York
    units: imperial
    cache: 15

- search:
    provider: duckduckgo
