---
# Widgets configuration

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    format: "%I:%M %p"
    dateFormat: "%A, %B %d"

- weather:
    provider: openmeteo
    location: local
    units: imperial
    show-icon: true
