---
# Widgets configuration

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    timeFormat: "%I:%M %p"
    dateFormat: "%A, %B %d"

- weather:
    provider: openmeteo
    latitude: 39.9259
    longitude: -75.0305
    units: imperial
    show-icon: true
